version: 2.1

executors:
  # declares a reusable executor
  poser_executor_php74:
    docker:
      - image: pugx/poser:php74
    working_directory: ~/app

  poser_executor_php80:
    docker:
      - image: pugx/poser:php80
    working_directory: ~/app

jobs:
  checkout_code:
    parameters:
      poser_executor:
        type: executor
    executor: << parameters.poser_executor >>
    steps:
      - checkout
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/app

  php_dependencies:
    parameters:
      poser_executor:
        type: executor
    executor: << parameters.poser_executor >>
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: install project dependencies
          command: composer install -n --no-progress --no-suggest
      - save_cache:
          paths:
            - ~/app/bin
            - ~/app/vendor
          key: v1-php-dependencies-{{ .Environment.CIRCLE_SHA1 }}

  lint_checks:
    parameters:
      poser_executor:
        type: executor
    executor: << parameters.poser_executor >>
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          name: Restore PHP Dependencies Cache
          keys:
            - v1-php-dependencies-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: run php-cs-fixer checks
          command: PHP_CS_FIXER_IGNORE_ENV=1 bin/php-cs-fixer fix --verbose --diff --dry-run

  phpspec_and_behat:
    parameters:
      poser_executor:
        type: executor
    executor: << parameters.poser_executor >>
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          name: Restore PHP Dependencies Cache
          keys:
            - v1-php-dependencies-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: run phpspec tests
          command: bin/phpspec run --format=pretty
      - run:
          name: run phpspec coverage tests
          command: XDEBUG_MODE=coverage bin/phpspec run -f progress -c phpspec-coverage.yml
      - store_artifacts:
          path: coverage
      - run:
          name: run behat checks
          command: bin/behat

workflows:
  build-and-test:
    jobs:
      - checkout_code:
          matrix:
            parameters:
              poser_executor: [ "poser_executor_php74", "poser_executor_php80" ]
      - php_dependencies:
          matrix:
            parameters:
              poser_executor: [ "poser_executor_php74", "poser_executor_php80" ]
          requires:
            - checkout_code
      - lint_checks:
          matrix:
            parameters:
              poser_executor: [ "poser_executor_php74", "poser_executor_php80" ]
          requires:
            - php_dependencies
      - phpspec_and_behat:
          matrix:
            parameters:
              poser_executor: [ "poser_executor_php74", "poser_executor_php80" ]
          requires:
            - php_dependencies
